# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: mark1024
service: serverless-url-shortener

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1 # Change if needed
  stage: ${opt:stage, 'dev'}
  environment:
    DYNAMODB_TABLE: short_urls_${self:provider.stage}
    SHORT_BASE_URL: ${env:SHORT_BASE_URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:CreateTable
        - dynamodb:UpdateTable
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:us-east-1:*:table/short_urls_${self:provider.stage}"
custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: false # Data is lost when the server stops
      migrate: true  # Automatically create tables
      seed: true
      dbPath: .dynamodb # Save data to a local file

plugins:
  - serverless-offline
  - serverless-dynamodb-local

functions:
  shorten:
    handler: src/handlers/shorten.shorten
    events:
      - httpApi:
          method: POST
          path: /shorten
  redirect:
    handler: src/handlers/redirect.redirect
    events:
      - httpApi:
          method: GET
          path: /{shortId}

resources:
  Resources:
    ShortUrlsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: short_urls_${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST


